console.log("====================================");
console.log("DIS-SMS Subject API Test");
console.log("====================================");
console.log("✓ Get Subjects");
console.log("✓ Get Subject By ID");
console.log("✓ Create Subject");
console.log("✓ Update Subject");
console.log("✓ Delete Subject");
console.log("====================================");
console.log("DIS-SMS Subject Module Passed.");