/**
 * Permission key stubs for future RBAC enforcement.
 * Not wired to routes or UI in Batch 1.
 */

const permissionsConfig = {
  roles: {
    SUPER_ADMIN: "SUPER_ADMIN",
    ADMIN: "ADMIN",
    TEACHER: "TEACHER",
    ACCOUNTANT: "ACCOUNTANT",
    STUDENT: "STUDENT",
    GUARDIAN: "GUARDIAN",
  },
  permissions: {
    DASHBOARD_VIEW: "dashboard.view",
    STUDENTS_VIEW: "students.view",
    STUDENTS_CREATE: "students.create",
    STUDENTS_UPDATE: "students.update",
    STUDENTS_DELETE: "students.delete",
    TEACHERS_VIEW: "teachers.view",
    DEPARTMENTS_VIEW: "departments.view",
    DEPARTMENTS_CREATE: "departments.create",
    DEPARTMENTS_UPDATE: "departments.update",
    DEPARTMENTS_DELETE: "departments.delete",
    SUBJECTS_VIEW: "subjects.view",
    SUBJECTS_CREATE: "subjects.create",
    SUBJECTS_UPDATE: "subjects.update",
    SUBJECTS_DELETE: "subjects.delete",
    TEACHER_SUBJECTS_VIEW: "teacher-subjects.view",
    TEACHER_SUBJECTS_CREATE: "teacher-subjects.create",
    TEACHER_SUBJECTS_UPDATE: "teacher-subjects.update",
    TEACHER_SUBJECTS_DELETE: "teacher-subjects.delete",
    CLASS_SUBJECTS_VIEW: "class-subjects.view",
    CLASS_SUBJECTS_CREATE: "class-subjects.create",
    CLASS_SUBJECTS_UPDATE: "class-subjects.update",
    CLASS_SUBJECTS_DELETE: "class-subjects.delete",
    TIMETABLES_VIEW: "timetables.view",
    TIMETABLES_CREATE: "timetables.create",
    TIMETABLES_UPDATE: "timetables.update",
    TIMETABLES_DELETE: "timetables.delete",
    ATTENDANCE_VIEW: "attendance.view",
    ATTENDANCE_CREATE: "attendance.create",
    ATTENDANCE_UPDATE: "attendance.update",
    ATTENDANCE_DELETE: "attendance.delete",
    ATTENDANCE_BULK: "attendance.bulk",
    ASSESSMENTS_VIEW: "assessments.view",
    ASSESSMENTS_CREATE: "assessments.create",
    ASSESSMENTS_UPDATE: "assessments.update",
    ASSESSMENTS_DELETE: "assessments.delete",
    ASSESSMENTS_SCORES: "assessments.scores",
    EXAMINATIONS_VIEW: "examinations.view",
    EXAMINATIONS_CREATE: "examinations.create",
    EXAMINATIONS_UPDATE: "examinations.update",
    EXAMINATIONS_DELETE: "examinations.delete",
    EXAMINATIONS_SCORES: "examinations.scores",
    EXAMINATIONS_LOCK: "examinations.lock",
    RESULTS_VIEW: "results.view",
    RESULTS_CREATE: "results.create",
    RESULTS_UPDATE: "results.update",
    RESULTS_DELETE: "results.delete",
    RESULTS_GENERATE: "results.generate",
    RESULTS_VERIFY: "results.verify",
    RESULTS_PUBLISH: "results.publish",
    RESULTS_LOCK: "results.lock",
    REPORT_CARDS_VIEW: "report-cards.view",
    REPORT_CARDS_CREATE: "report-cards.create",
    REPORT_CARDS_UPDATE: "report-cards.update",
    REPORT_CARDS_DELETE: "report-cards.delete",
    REPORT_CARDS_GENERATE: "report-cards.generate",
    REPORT_CARDS_VERIFY: "report-cards.verify",
    REPORT_CARDS_PUBLISH: "report-cards.publish",
    REPORT_CARDS_LOCK: "report-cards.lock",
    PROMOTIONS_VIEW: "promotions.view",
    PROMOTIONS_CREATE: "promotions.create",
    PROMOTIONS_UPDATE: "promotions.update",
    PROMOTIONS_DELETE: "promotions.delete",
    PROMOTIONS_RECOMMEND: "promotions.recommend",
    PROMOTIONS_APPROVE: "promotions.approve",
    PROMOTIONS_EXECUTE: "promotions.execute",
    ENROLLMENTS_VIEW: "enrollments.view",
    ENROLLMENTS_CREATE: "enrollments.create",
    ENROLLMENTS_UPDATE: "enrollments.update",
    ENROLLMENTS_DELETE: "enrollments.delete",
    CLASSES_VIEW: "classes.view",
    FINANCE_VIEW: "finance.view",
    REPORTS_VIEW: "reports.view",
    SETTINGS_MANAGE: "settings.manage",
    SCHOOL_SETTINGS_VIEW: "school-settings.view",
    SCHOOL_SETTINGS_UPDATE: "school-settings.update",
    AUDIT_VIEW: "audits.view",
    NOTIFICATIONS_VIEW: "notifications.view",
    CONFIG_MANAGE: "config.manage",
    UPLOADS_MANAGE: "uploads.manage",
    USERS_MANAGE: "users.manage",
    ROLES_MANAGE: "roles.manage",
  },
};

export default permissionsConfig;
