const API = {
    BASE_URL: "http://localhost:5000/api",

    AUTH: {
        LOGIN: "/auth/login",
        LOGOUT: "/auth/logout",
        REFRESH: "/auth/refresh-token",
        ME: "/auth/me",
    },

    STUDENTS: {
        LIST: "/students",
        CREATE: "/students",
        SEARCH: "/students/search",
        ARCHIVED: "/students/archived",
        DETAIL: (id) => `/students/${id}`,
        UPDATE: (id) => `/students/${id}`,
        DELETE: (id) => `/students/${id}`,
        RESTORE: (id) => `/students/${id}/restore`,
    },

    GUARDIANS: {
        LIST: "/guardians",
        CREATE: "/guardians",
        ARCHIVED: "/guardians/archived",
        DETAIL: (id) => `/guardians/${id}`,
        UPDATE: (id) => `/guardians/${id}`,
        DELETE: (id) => `/guardians/${id}`,
        RESTORE: (id) => `/guardians/${id}/restore`,
        BY_STUDENT: (studentId) => `/students/${studentId}/guardians`,
        LINK: (studentId) => `/students/${studentId}/guardians`,
        UNLINK: (studentId, guardianId) =>
            `/students/${studentId}/guardians/${guardianId}`,
    },

    CLASSES: {
        LIST: "/classes",
        CREATE: "/classes",
        ARCHIVED: "/classes/archived",
        DETAIL: (id) => `/classes/${id}`,
        UPDATE: (id) => `/classes/${id}`,
        DELETE: (id) => `/classes/${id}`,
        RESTORE: (id) => `/classes/${id}/restore`,
    },

    SUBJECTS: {
        LIST: "/subjects",
        CREATE: "/subjects",
        ARCHIVED: "/subjects/archived",
        DETAIL: (id) => `/subjects/${id}`,
        UPDATE: (id) => `/subjects/${id}`,
        DELETE: (id) => `/subjects/${id}`,
        RESTORE: (id) => `/subjects/${id}/restore`,
    },

    TEACHER_SUBJECTS: {
        LIST: "/teacher-subjects",
        CREATE: "/teacher-subjects",
        ARCHIVED: "/teacher-subjects/archived",
        DETAIL: (id) => `/teacher-subjects/${id}`,
        UPDATE: (id) => `/teacher-subjects/${id}`,
        DELETE: (id) => `/teacher-subjects/${id}`,
        RESTORE: (id) => `/teacher-subjects/${id}/restore`,
    },

    CLASS_SUBJECTS: {
        LIST: "/class-subjects",
        CREATE: "/class-subjects",
        ARCHIVED: "/class-subjects/archived",
        DETAIL: (id) => `/class-subjects/${id}`,
        UPDATE: (id) => `/class-subjects/${id}`,
        DELETE: (id) => `/class-subjects/${id}`,
        RESTORE: (id) => `/class-subjects/${id}/restore`,
    },

    TIMETABLES: {
        LIST: "/timetables",
        CREATE: "/timetables",
        VIEW: "/timetables/view",
        DETAIL: (id) => `/timetables/${id}`,
        UPDATE: (id) => `/timetables/${id}`,
        DELETE: (id) => `/timetables/${id}`,
    },

    ATTENDANCE: {
        LIST: "/attendance",
        CREATE: "/attendance",
        BULK: "/attendance/bulk",
        ROSTER: "/attendance/roster",
        STATS: "/attendance/stats",
        DETAIL: (id) => `/attendance/${id}`,
        UPDATE: (id) => `/attendance/${id}`,
        DELETE: (id) => `/attendance/${id}`,
    },

    ASSESSMENTS: {
        LIST: "/assessments",
        CREATE: "/assessments",
        ARCHIVED: "/assessments/archived",
        STATS: "/assessments/stats",
        DETAIL: (id) => `/assessments/${id}`,
        ROSTER: (id) => `/assessments/${id}/roster`,
        SCORES_BULK: (id) => `/assessments/${id}/scores/bulk`,
        UPDATE: (id) => `/assessments/${id}`,
        DELETE: (id) => `/assessments/${id}`,
        RESTORE: (id) => `/assessments/${id}/restore`,
    },

    EXAMINATIONS: {
        LIST: "/examinations",
        CREATE: "/examinations",
        ARCHIVED: "/examinations/archived",
        STATS: "/examinations/stats",
        DETAIL: (id) => `/examinations/${id}`,
        ROSTER: (id) => `/examinations/${id}/roster`,
        SCORES_BULK: (id) => `/examinations/${id}/scores/bulk`,
        UPDATE: (id) => `/examinations/${id}`,
        DELETE: (id) => `/examinations/${id}`,
        RESTORE: (id) => `/examinations/${id}/restore`,
        LOCK: (id) => `/examinations/${id}/lock`,
        UNLOCK: (id) => `/examinations/${id}/unlock`,
    },

    RESULTS: {
        LIST: "/results",
        CREATE: "/results",
        ARCHIVED: "/results/archived",
        STATS: "/results/stats",
        WEIGHTINGS: "/results/weightings",
        BROADSHEET: "/results/broadsheet",
        MERIT_LIST: "/results/merit-list",
        STUDENT_PROFILE: (studentId) => `/results/student-profile/${studentId}`,
        GENERATE: "/results/generate",
        VERIFY: "/results/verify",
        UNVERIFY: "/results/unverify",
        PUBLISH: "/results/publish",
        UNPUBLISH: "/results/unpublish",
        LOCK: "/results/lock",
        UNLOCK: "/results/unlock",
        RECALCULATE: "/results/recalculate-positions",
        DETAIL: (id) => `/results/${id}`,
        UPDATE: (id) => `/results/${id}`,
        DELETE: (id) => `/results/${id}`,
        RESTORE: (id) => `/results/${id}/restore`,
    },

        REPORT_CARDS: {
        LIST: "/report-cards",
        ARCHIVED: "/report-cards/archived",
        STATS: "/report-cards/stats",
        TEMPLATES: "/report-cards/templates",
        GENERATE: "/report-cards/generate",
        GENERATE_BULK: "/report-cards/generate-bulk",
        VERIFY: "/report-cards/verify",
        UNVERIFY: "/report-cards/unverify",
        PUBLISH: "/report-cards/publish",
        UNPUBLISH: "/report-cards/unpublish",
        LOCK: "/report-cards/lock",
        UNLOCK: "/report-cards/unlock",
        DETAIL: (id) => `/report-cards/${id}`,
        PREVIEW: (id) => `/report-cards/${id}/preview`,
        UPDATE: (id) => `/report-cards/${id}`,
        DELETE: (id) => `/report-cards/${id}`,
        RESTORE: (id) => `/report-cards/${id}/restore`,
    },

    STUDENT_PROMOTIONS: {
        LIST: "/student-promotions",
        ARCHIVED: "/student-promotions/archived",
        GRADUATES: "/student-promotions/graduates",
        STATS: "/student-promotions/stats",
        HISTORY: (studentId) => `/student-promotions/history/${studentId}`,
        RECOMMEND: "/student-promotions/recommend",
        APPROVE: "/student-promotions/approve",
        UNAPPROVE: "/student-promotions/unapprove",
        EXECUTE: "/student-promotions/execute",
        CANCEL: "/student-promotions/cancel",
        DETAIL: (id) => `/student-promotions/${id}`,
        UPDATE: (id) => `/student-promotions/${id}`,
        DELETE: (id) => `/student-promotions/${id}`,
        RESTORE: (id) => `/student-promotions/${id}/restore`,
    },

    GRADES: {
        LIST: "/grades",
        CREATE: "/grades",
        DETAIL: (id) => `/grades/${id}`,
        SCALES: "/grades/scales",
        SCALE_DETAIL: (id) => `/grades/scales/${id}`,
        SCALE_DEFAULT: (id) => `/grades/scales/${id}/default`,
    },

    ENROLLMENTS: {
        LIST: "/enrollments",
        CREATE: "/enrollments",
        ARCHIVED: "/enrollments/archived",
        DETAIL: (id) => `/enrollments/${id}`,
        UPDATE: (id) => `/enrollments/${id}`,
        DELETE: (id) => `/enrollments/${id}`,
        RESTORE: (id) => `/enrollments/${id}/restore`,
    },

    TEACHERS: {
        LIST: "/teachers",
        CREATE: "/teachers",
        SEARCH: "/teachers/search",
        ARCHIVED: "/teachers/archived",
        DETAIL: (id) => `/teachers/${id}`,
        UPDATE: (id) => `/teachers/${id}`,
        DELETE: (id) => `/teachers/${id}`,
        RESTORE: (id) => `/teachers/${id}/restore`,
    },

    DEPARTMENTS: {
        LIST: "/departments",
        CREATE: "/departments",
        SEARCH: "/departments/search",
        ARCHIVED: "/departments/archived",
        DETAIL: (id) => `/departments/${id}`,
        UPDATE: (id) => `/departments/${id}`,
        DELETE: (id) => `/departments/${id}`,
        RESTORE: (id) => `/departments/${id}/restore`,
    },

    ACADEMIC_YEARS: {
        LIST: "/academic-years",
        CREATE: "/academic-years",
        ARCHIVED: "/academic-years/archived",
        DETAIL: (id) => `/academic-years/${id}`,
        UPDATE: (id) => `/academic-years/${id}`,
        DELETE: (id) => `/academic-years/${id}`,
        RESTORE: (id) => `/academic-years/${id}/restore`,
    },

    TERMS: {
        LIST: "/terms",
        CREATE: "/terms",
        ARCHIVED: "/terms/archived",
        DETAIL: (id) => `/terms/${id}`,
        UPDATE: (id) => `/terms/${id}`,
        DELETE: (id) => `/terms/${id}`,
        ACTIVATE: (id) => `/terms/${id}/activate`,
        RESTORE: (id) => `/terms/${id}/restore`,
    },

    SCHOOL_SETTINGS: {
        GET: "/school-settings",
        UPDATE: "/school-settings",
    },

    SETTINGS: {
        LIST: "/settings",
        MAP: "/settings/map",
        BULK: "/settings/bulk",
        BY_KEY: (key) => `/settings/key/${encodeURIComponent(key)}`,
        DETAIL: (id) => `/settings/${id}`,
        CREATE: "/settings",
        UPDATE: (id) => `/settings/${id}`,
        DELETE: (id) => `/settings/${id}`,
    },

    AUDITS: {
        LIST: "/audits",
        DETAIL: (id) => `/audits/${id}`,
    },

    NOTIFICATIONS: {
        LIST: "/notifications",
        UNREAD_COUNT: "/notifications/unread-count",
        MARK_ALL_READ: "/notifications/mark-all-read",
        DETAIL: (id) => `/notifications/${id}`,
        CREATE: "/notifications",
        MARK_READ: (id) => `/notifications/${id}/read`,
        UPDATE: (id) => `/notifications/${id}`,
        DELETE: (id) => `/notifications/${id}`,
    },

    UPLOADS: {
        LIST: "/uploads",
        CREATE: "/uploads",
        DETAIL: (id) => `/uploads/${id}`,
        DELETE: (id) => `/uploads/${id}`,
    },
};

export default API;
